


[params]
primaryColorTheme = "LightBlue"
secondaryColorTheme = "Amber"

surfaceColor = "#FAFAFA"
backgroundColor = "#EEEEEE"

onPrimaryColor = "#FFFFFF"
onLightPrimaryColor = "#616161"
onDarkPrimaryColor = "#FFFFFF"

onSecondaryColor = "#FFFFFF"
onLightSecondaryColor = "#FFFFFF"
onDarkSecondaryColor = "#FFFFFF"

baseTextColor = "#757575"
lightTextColor = "#9E9E9E"
darkTextColor = "#616161"

shadowColor = "#00000040"


# primary color detail setting
# primaryColor = "#8BC34A"
# lightPrimaryColor = "#DCEDC8"
# darkPrimaryColor = "#689F38"

# secondary color detail setting
# secondaryColor = "#FFC107"
# lightSecondaryColor = "#FFECB3"
# darkSecondaryColor = "#FFA000"
